[package]
name = "fmp"
description = "A simple command-line password manager written in Rust."
repository = "https://github.com/TT1882/Forgot-My-Password.git"
authors = ["Luke Wilkinson <wilkinsonluke@proton.me>"]
version = "1.3.0"
edition = "2024"
license = "GPL-3.0"
keywords = ["password-manager", "cli", "crypto", "cryptography", "rust"]

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
dirs = "6.0.0"
env_logger = "0.11.8"
fs_extra = "1.3.0"
gpgme = "0.11.0"
libc = "0.2.172"
log = "0.4"
prettytable = "0.10.0"
rand = "0.9.1"
rpassword = "7.4.0"
secrecy = "0.10.3"
tempfile = "3.10.0"
windows = { version = "0.61.1", optional = true }
zeroize = "1.8.1"
