[package]
name = "fmp"
version = "0.1.0"
edition = "2024"

[dependencies]
zeroize = "1.8.1"
gpgme = "0.11.0"
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
prettytable = "0.10.0"
rpassword = "7.4.0"
libc = "0.2.172"
secrecy = "0.10.3"
tempfile = "3.10.0"
dirs = "6.0.0"
rand = "0.9.1"
fs_extra = "1.3.0"
